export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGOREIS_START: 'category/FETCH_CATEGORIES_START',
  FETCH_CATEGOREIS_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGOREIS_FAILED: 'category/FETCH_CATEGORIES_FAILED',
};
